# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and canary builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ["v1.x", "canary"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify Formatting
        run: deno fmt --check --ignore=docs/

      - name: Run Linter
        run: deno lint --ignore=docs/

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Run Tests
        run: deno test -A --unstable

  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ["v1.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Create Coverage Files
        run: deno test --coverage=coverage

      - name: Create Coverage Report
        run: deno coverage ./coverage --ignore=docs/ --lcov > coverage.lcov

      - name: Collect Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.lcov